### ISSUE TITLE
Congratulations and a question about ep_auth_author and ep_ldapauth.

### ISSUE THREAD

**Issue by SMIBoy** [lsowen/ep_auth_author#1]
Hello lsowen,

First of all, thank you for this awesome plugin!!

Is it possible to use ep_auth_author with ep_ldapauth plugin? It would be incredible to access etherpad-lite with ep_ldapauth and "remember" the authorname and colors for every user with your plugin.

Thank you very much.

**Comment by lsowen** [comment]
Hi @Sergio3,

Glad you liked it.  While I haven't attempted to, I believe it would be unlikely that ep_ldapauth and ep_auth_author could work together.  They could both be enabled at the same time, but because they both utilize the auth hook, only one would actually log in a specific user.

It is possible that ep_auth_author could be reworked to be a more general plugin, but I'm not sure.

**Comment by lsowen** [comment]
Closing for now.
