### ISSUE TITLE
ep_auth_author released npm does not match github repo

### ISSUE THREAD

**Issue by apenwarr** [lsowen/ep_auth_author#5]
The github repo contains a documentation fix to recommend the "author_name" setting instead of "authorName", and identifies itself as 0.0.2.  The released npm identifies itself as 0.0.4, but does not contain this documentation fix (which is very confusing and probably makes the plugin unusable to most people!).

Did you forget to release the latest repo?  Is there another repo that 0.0.4 was released from, which does not contain the documentation fix?

**Comment by lsowen** [comment]
Hi @apenwarr thanks for bringing this to my attention.  I was able to find my local repo, and there actually aren't any code changes from 85d888d0c67ed1dee1bdb6a3fdaefe361ec415b0.  

This has been a while ago, but I think I bumped the version number only because I was having some issues publishing the package to npm.

If you want, bump the version to 0.0.5 and I'll release an updated version on npm.

**Comment by apenwarr** [comment]
Sure, here you go: https://github.com/lsowen/ep_auth_author/pull/6

**Comment by lsowen** [comment]
Just merged and pushed the updated package to npm.  Thanks!
